# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DreamReader' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
# Pods for DreamReader

pod 'MMDrawerController', '~> 0.6.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'AFNetworking', '~> 3.1.0'

pod 'IQKeyboardManager', '~> 4.0.8'
pod 'LCActionSheet', '~> 2.7.2'
#友盟分享
#pod ‘UMengUShare/UI’
pod 'UMengUShare/Social/Sina'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'MJRefresh', '~> 3.1.12'
pod 'MBProgressHUD', '~> 1.0.0'
#夜间模式
pod 'DKNightVersion', '~> 2.4.2'
#滑动返回
pod 'FDFullscreenPopGesture', '1.1'
#下载
pod 'WHCNetWorkKit', '~> 0.0.3'
#网络监测
pod 'Reachability', '~> 3.2'
pod 'QMUIKit', '~> 1.2'


  target 'DreamReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DreamReaderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
